name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.17.1]
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Build
        run: |
          npm ci
          npm run lint
          npm run build

      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY}}
          pass: ${{ secrets.FTP_PASSWORD}}
          first_ssh: |
            rm -rf /www/wwwroot/webdict/assets /www/wwwroot/webdict/index.html
          scp: |
            "./dist/" => ${{ secrets.REMOTE_DIR }}
